_BASE_: "../base-prompt.yaml"
RUN_N_TIMES: 10
DATA:
  NAME: "CUB_200_2011"
  DATAPATH: "VPTDataRelease/data/cub"  #TODO: need to specify here
  NUMBER_CLASSES: 20
  MULTILABEL: False
MODEL:
  TYPE: "vit"
SOLVER:
  BASE_LR: 0.1
  WEIGHT_DECAY: 0.01